### ISSUE TITLE
choose columns which may or may not exist in data by col_select in vroom

### ISSUE THREAD

**Issue by Nataliannash** [tidyverse/vroom#450]
Hi there,

I want to use vroom to select some columns from large number of .csv files, no matter if columns exist in all .csv files or not. 
The following command just works when all selected columns exist in all csv files and there is error if I add  columns which does not exist at least in one csv file. 

It would appreciated if you could help me to find a way to solve this problem, for example by skipping the csv files which does not have all selected columns, or put NA for the missed columns for csv without specific columns.

y = map(all_files, ~vroom(.x, col_select = c('X', 'Y' , 'Z' )) , .id = 'filenum')

Error in `chr_as_locations()`:                                                                                                                                    
! Can't subset columns that don't exist.

Thank you,
Nat

**Comment by jennybc** [comment]
Looking back over previous vroom issues, this feels fairly similar to #305.

(BTW, the reprex (reproducible example) given there is the ideal basis for really talking about these things. So if you want to pursue this further, please state your exact challenge with executable code like that in a new issue.)

But at this point, I think what you're seeing is just how `col_select` works and we have no concrete plans to work around it. Since you're already using `map()`, instead of vroom's ability to read from multiple data sources, you probably need to implement the flexibility you want in a custom wrapper around `vroom()`.

**Comment by jennybc** [comment]
Having learned more about tidyselect when reviewing #457, I now know that `tidyselect::vars_select()` (and `tidyselect::eval_select()`, which is preferred now, #459) has a `.strict` argument that controls exactly this. `.strict` is currently set to `TRUE` in vroom (via a default):

https://github.com/tidyverse/vroom/blob/a8abdc1dc7a27c271b985d253e1a4fd0f732149e/R/col_types.R#L363

Although I'm adding this bit of context, I still have no inclination to change this to `.strict = FALSE` or to somehow expose this to the user.
